
services:
###> doctrine/doctrine-bundle ###

###< doctrine/doctrine-bundle ###

###> symfony/mailer ###

###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "3000:80"
###< symfony/mercure-bundle ###
